Add collaborators for new Bichard repo
ministryofjustice/github-collaborators pull request #169
Opened 2021-04-28 16:43 UTC by bjpirt

2021-04-29 08:59 UTC, bjpirt commented
@ministryofjustice/operations-engineering Any chance we could get a review on this please?

2021-04-29 09:57 UTC, jakemulley approved these changes

2021-04-29 09:58 UTC, jakemulley requested changes
You'll need to add a file extension (`.tf`) to the file, else it won't run.

2021-04-30 10:21 UTC, bjpirt commented
@jakemulley Doh! Not sure how I missed that off - ready for re-review now

2021-04-30 10:32 UTC, jakemulley approved these changes

2021-04-30 10:32 UTC, merged