Add an external collaborator
ministryofjustice/github-collaborators pull request #2084
Opened 2024-05-30 14:39 UTC by andyrogers1973

Gregory Whiting will be given access to yjaf-terraform repo

[Issue #2083](https://github.com/ministryofjustice/github-collaborators/issues/2083)

2024-05-30 14:46 UTC, tamsinforbes requested changes
Waiting clarification on access level required

2024-05-30 14:46 UTC, tamsinforbes commented on terraform/yjaf-terraform.tf
> +      added_by     = "andy.rogers@digital,justice,gov.uk"
```suggestion
      added_by     = "andy.rogers@digital.justice.gov.uk"
```

2024-05-30 15:12 UTC, AntonyBishop submitted a review, later dismissed
We can't be the `added_by` user. Access need to be authorised by David.Hall@yjb.gov.uk

2024-05-31 10:44 UTC, tamsinforbes approved these changes
Received approval via David Halls deputies.

2024-05-31 10:45 UTC, merged