Update Sol-Tec Users to Content and Cloud and renew access
ministryofjustice/github-collaborators pull request #378
Opened 2021-12-08 12:06 UTC by HughSolTec

2021-12-08 12:24 UTC, ben-al approved these changes
LGTM

2021-12-08 12:29 UTC, ben-al requested changes

2021-12-08 12:29 UTC, ben-al commented on terraform/MOJ-PTTP-DevicesAndApps-Pipeline-Windows10Apps.tf
> -  collaborators = [
This has to be present

2021-12-09 09:16 UTC, HughSolTec commented on terraform/MOJ-PTTP-DevicesAndApps-Pipeline-Windows10Apps.tf
> -  collaborators = [
Have updated . thank you :)

2021-12-09 10:14 UTC, ben-al commented
@HughSolTec Morning mate - looks like some S3 credentials have expired or something, looking into this now. Apologies for the blocker.

2021-12-09 10:20 UTC, ben-al commented
@HughSolTec Hi Hugh - i've just been informed that PRs from forks do not work, could you PR from branch please? Incredibly sorry for the inconvenience, I will update the docs to make this more clear.

2021-12-09 10:36 UTC, HughSolTec commented
> 

Hi Ben, I don't think I have permissions to create a new branch as this is what I initially tried before forking. many thanks

2021-12-09 11:01 UTC, ben-al commented
Ah ok - i'll make it for you, will tag you in it for confirmation.

2021-12-09 11:33 UTC, ben-al commented
I merged a branch PR for you: https://github.com/ministryofjustice/github-collaborators/pull/380

Let me know if there are any problems with it, will close this.

2021-12-09 11:33 UTC, closed without merging